import { useEffect,useRef,useState } from 'react'
import { motion,animate,useReducedMotion } from 'framer-motion'
import { Play,Pause,RotateCcw,ArrowRight } from 'lucide-react'
import { useFarm,SCENARIOS,type ScenarioKey } from '../FarmContext'
import { useStore } from '../store'
import { usePerm } from '../auth'
import { fieldLabel } from '../workflow-model'
import { PageHeader } from '../components/workflow'
import { FarmMapSVG } from '../components/FarmMapSVG'
import { SuccessMark } from '../components/motion'

export default function Demo(){const {state,run,startScenario,pauseScenario,resumeScenario,cancelScenario,openTask}=useFarm(),{setScreen,valves}=useStore(),{needAdmin}=usePerm();const scene=run?SCENARIOS[run.kind]:SCENARIOS.irrigation;
 const reduced=useReducedMotion(),[progress,setProgress]=useState(0),progressRef=useRef(0),sceneId=useRef('');
 useEffect(()=>{if(sceneId.current!==run?.id){sceneId.current=run?.id??'';progressRef.current=0;setProgress(0)}if(!run?.running&&!run?.done)return;const target=(run?.step??0)*20;const control=animate(progressRef.current,target,{duration:reduced?0:1.9,ease:'linear',onUpdate:value=>{progressRef.current=value;setProgress(value)}});return()=>control.stop()},[run?.id,run?.step,run?.running,run?.done,reduced]);
 return <div className="work-page"><PageHeader title="场景演示" sub="从发现问题，到作业完成"/><div className="demo-intro"><span className="eyebrow">FARM IN MOTION</span><h2>看见一次农事<br/>如何顺利完成。</h2><p>本机仿真演示 · 自动生成可查看的任务和记录</p></div><div className="scenario-grid">{(Object.entries(SCENARIOS) as [ScenarioKey,typeof scene][]).map(([key,s])=><button key={key} aria-pressed={run?.kind===key} disabled={!!run?.running} onClick={()=>needAdmin()&&startScenario(key)}><span>{fieldLabel(s.fieldId)}</span><b>{s.label}</b><Play size={17}/></button>)}</div>{run&&<><div className="work-card demo-map"><FarmMapSVG layers={{fields:true,monitors:true,irrigation:true}} selectedField={scene.fieldId} fieldMoisture={state.moisture} fieldValves={Object.fromEntries(['A1','A2','B1','B2','C1'].map((id,i)=>[id,valves[i]]))} patrol={run.kind==='patrol'?{progress,running:run.running}:undefined}/><div className="demo-status"><div><span>{run.done?'演示完成':run.running?'正在演示':'已暂停'}</span><motion.h3 key={run.step} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}>{scene.steps[run.step]}</motion.h3></div>{run.done?<SuccessMark size={36}/>:<b>{run.step+1}<small>/6</small></b>}</div></div><ol className="scenario-steps">{scene.steps.map((step,i)=><li key={step} data-done={i<=run.step}><span>{i<run.step?'✓':i+1}</span><div><b>{step}</b><small>{i===run.step?(run.done?'已完成':run.running?'执行中':'等待继续'):i<run.step?'已记录':'等待执行'}</small></div></li>)}</ol><div className="work-actions">{!run.done&&<button className="work-primary" onClick={run.running?pauseScenario:resumeScenario}>{run.running?<Pause size={16}/>:<Play size={16}/>} {run.running?'暂停演示':'继续演示'}</button>}{run.done&&<button onClick={()=>startScenario(run.kind)}><RotateCcw size={16}/>再次演示</button>}<button onClick={cancelScenario}>结束演示</button></div><div className="work-actions"><button disabled={run.step<1} onClick={()=>openTask(`task-${run.id}`)}>关联任务<ArrowRight size={14}/></button><button onClick={()=>setScreen('history')}>查看时间轴<ArrowRight size={14}/></button></div><p className="muted">暂停后可继续；切换页面时演示仍会推进，应用进入后台时暂停计时。结束演示会保留已生成的任务和记录。</p></>}</div>}
