import { StoredPhoto } from '../../../shared/reference-media'
import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight,Droplets,Leaf,ClipboardList,History } from 'lucide-react'
import { FIELDS } from '../farm-data'
import { useFarm } from '../FarmContext'
import { useStore } from '../store'
import { fieldById,fieldLabel } from '../workflow-model'
import { PageHeader,Sheet,PhotoGallery,EmptyState,InteractiveChart } from '../components/workflow'
import { FarmMapSVG } from '../components/FarmMapSVG'
import { Reveal } from '../components/motion'

export function FieldCard({id}:{id:string}){const {state,openField}=useFarm(),f=fieldById(id);return <motion.button layout className="field-directory-card" onClick={()=>openField(id)} aria-label={`打开 ${fieldLabel(id)} 档案`}><motion.div layoutId={`field-image-${id}`} className="field-directory-map"><FarmMapSVG currentMoisture={state.moisture} layers={{fields:true,monitors:false,irrigation:false}} selectedField={id}/></motion.div><div><span className="eyebrow">FIELD / {f.id}</span><h3>{f.crop}<ArrowUpRight size={16}/></h3><p>{f.area} 亩 · {f.stageName}</p><footer><span><Droplets size={12}/>{state.moisture[id].toFixed(0)}%</span><span><Leaf size={12}/>{f.health} 分</span></footer></div></motion.button>}
export default function Fields(){const [query,setQuery]=useState('');return <div className="work-page"><PageHeader title="地块档案" sub="一块田，一份完整的生长记录"/><input className="work-input" aria-label="搜索地块" placeholder="搜索编号、作物或品种" value={query} onChange={e=>setQuery(e.target.value)}/><div className="field-directory">{FIELDS.filter(f=>`${f.id}${f.crop}${f.variety}`.includes(query)).map(f=><Reveal key={f.id}><FieldCard id={f.id}/></Reveal>)}</div>{!FIELDS.some(f=>`${f.id}${f.crop}${f.variety}`.includes(query))&&<EmptyState title="未找到地块" detail="试试 A1、水稻或品种名称。"/>}</div>}
export function FieldDossier(){const {dossier,closeField,state,openTask,selectField}=useFarm();const {setScreen}=useStore();const [photoIndex,setPhotoIndex]=useState<number|null>(null);const f=fieldById(dossier??'A1'),events=state.events.filter(e=>e.fieldId===f.id),tasks=state.tasks.filter(t=>t.fieldId===f.id),photos=events.filter(e=>e.photo).map(e=>({id:e.id,src:e.photo!,note:e.detail}));const moisture=state.moisture[f.id];return <><Sheet open={!!dossier} onClose={closeField} title={`${fieldLabel(f.id)} · 地块档案`}><motion.div layoutId={`field-image-${f.id}`} className="dossier-map"><FarmMapSVG currentMoisture={state.moisture} layers={{fields:true,monitors:true,irrigation:true}} selectedField={f.id}/></motion.div><div className="dossier-intro"><span className="eyebrow">{f.variety}</span><h3>{f.area} 亩 · {f.stageName}</h3><p>预计收获 {f.harvest} · 下一农事：{f.nextAction}</p></div><div className="work-metrics"><div><small>当前墒情</small><b>{moisture.toFixed(0)}<em>%</em></b></div><div><small>土壤 pH</small><b>{f.ph}</b></div><div><small>健康度</small><b>{f.health}</b></div><div><small>待办任务</small><b>{tasks.filter(t=>t.status!=='已完成').length}</b></div></div><h3 className="work-section-title">墒情趋势 <small>演示读数</small></h3><InteractiveChart values={[moisture-5,moisture-3,moisture-4,moisture-1,moisture]} labels={['前4天','前3天','前2天','昨天','当前']}/><div className="work-actions"><button onClick={()=>{selectField(f.id);closeField();setScreen('irrigation')}}><Droplets size={15}/>灌溉</button><button onClick={()=>openTask()}><ClipboardList size={15}/>安排任务</button><button onClick={()=>{closeField();setScreen('history')}}><History size={15}/>作业历史</button></div><h3 className="work-section-title">关联任务</h3>{tasks.length?tasks.slice(0,5).map(t=><button className="work-row" key={t.id} onClick={()=>openTask(t.id)}><span><b>{t.title}</b><small>{t.assignee||'未分派'} · {t.due}</small></span><span className="status-pill">{t.status}</span></button>):<EmptyState title="暂无任务" detail="可为这块田安排一次巡检。"/>}<h3 className="work-section-title">作业照片</h3>{photos.length?<div className="photo-strip">{photos.map((p,i)=><button key={p.id} onClick={()=>setPhotoIndex(i)}><StoredPhoto src={p.src} alt={p.note}/></button>)}</div>:<p className="muted">完成采样或上传任务照片后，会在这里汇总。</p>}<h3 className="work-section-title">最近动态</h3>{events.slice(0,6).map(e=><div className="event-line" key={e.id}><i/><div><b>{e.title}</b><p>{e.detail}</p><small>{new Date(e.at).toLocaleString('zh-CN')}</small></div></div>)}</Sheet><PhotoGallery photos={photos} index={photoIndex} onClose={()=>setPhotoIndex(null)}/></>}
