import { StoredPhoto } from '../../../shared/reference-media'
import { useEffect,useState } from 'react'
import { AnimatePresence,motion,useReducedMotion } from 'framer-motion'
import { Plus,Camera,CheckCircle2,Search,ArrowRight } from 'lucide-react'
import { toast } from 'sonner'
import { useFarm } from '../FarmContext'
import { usePerm } from '../auth'
import { PEOPLE,DEVICES,TASK_STATES,fieldLabel,today,type TaskStatus } from '../workflow-model'
import { PageHeader,FieldSelect,Sheet,EmptyState,PhotoGallery,readPhoto } from '../components/workflow'
import TaskResult from '../components/TaskResult'
import { SuccessMark } from '../components/motion'

export default function Tasks(){
 const reduced=useReducedMotion()
 const {state,activeField,taskFocus,createTask,assignTask,advanceTask,uploadPhoto}=useFarm();const {isAdmin,needLogin,needAdmin}=usePerm()
 const [filter,setFilter]=useState<TaskStatus|'全部'>('全部'),[field,setField]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(taskFocus),[creating,setCreating]=useState(false),[photoIndex,setPhotoIndex]=useState<number|null>(null),[busy,setBusy]=useState(false),[photoError,setPhotoError]=useState('')
 const [draft,setDraft]=useState({title:'',fieldId:activeField,kind:'巡检',assignee:PEOPLE[0],device:DEVICES[0],due:today(),note:''})
 const [assignee,setAssignee]=useState(PEOPLE[0]),[device,setDevice]=useState(DEVICES[0])
 useEffect(()=>{setSelected(taskFocus)},[taskFocus])
 const task=state.tasks.find(t=>t.id===selected);const list=state.tasks.filter(t=>(filter==='全部'||t.status===filter)&&(field==='all'||t.fieldId===field)&&`${t.title}${t.assignee}${t.fieldId}${t.note}`.includes(query))
 const ordered=[...list].sort((a,b)=>Number(a.status==='已完成')-Number(b.status==='已完成') || b.updatedAt-a.updatedAt)
 const photos=task?.photos.map(p=>({id:p.id,src:p.src,note:p.note}))??[]
 const advance=()=>{if(!task)return;const next=TASK_STATES[TASK_STATES.indexOf(task.status)+1];if(!next)return;if(next==='已完成'&&!needAdmin())return;if(!needLogin())return;if((next==='待验收'||next==='已完成')&&!task.photos.length){toast('请先上传作业照片，再提交验收');return}advanceTask(task.id,next);toast(next==='已完成'?'已验收，关联预警同步解决':`任务已更新为${next}`)}
 const file=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!task)return;setBusy(true);setPhotoError('');try{uploadPhoto(task.id,await readPhoto(f),'现场作业照片');toast('照片已关联任务与地块')}catch(err){setPhotoError((err as Error).message)}finally{setBusy(false);e.target.value=''}}
 return <div className="work-page"><PageHeader title="农事任务" sub="分派、执行、验收，每一步都有记录"><button aria-label="新建任务" className="icon-button primary" onClick={()=>{if(needLogin()){setDraft(d=>({...d,fieldId:activeField,assignee:isAdmin?d.assignee:''}));setCreating(true)}}}><Plus size={20}/></button></PageHeader><div className="work-metrics"><div><small>总任务</small><b>{state.tasks.length}</b></div><div><small>执行中</small><b>{state.tasks.filter(t=>t.status==='执行中').length}</b></div><div><small>待验收</small><b>{state.tasks.filter(t=>t.status==='待验收').length}</b></div><div><small>完成率</small><b>{Math.round(state.tasks.filter(t=>t.status==='已完成').length/Math.max(1,state.tasks.length)*100)}<em>%</em></b></div></div><div className="work-search"><Search size={16}/><input aria-label="搜索任务" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索任务、人员或地块"/></div><FieldSelect value={field} onChange={setField} all/><div className="filter-strip">{(['全部',...TASK_STATES] as const).map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}</button>)}</div><div className="task-list"><AnimatePresence mode="popLayout">{ordered.flatMap((t,index)=>[...(index===0 || (t.status==='已完成' && ordered[index-1].status!=='已完成') ? [<motion.div layout key={t.status==='已完成'?'done-heading':'pending-heading'} className="task-group-heading"><b>{t.status==='已完成'?'已完成归档':'进行中的农事'}</b><span>{list.filter(item=>(item.status==='已完成')===(t.status==='已完成')).length} 项</span></motion.div>] : []),<motion.button layout={!reduced} key={t.id} data-task-id={t.id} initial={{opacity:0,y:reduced?0:14}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:reduced?1:.94}} transition={{duration:reduced?0:.35}} className={`task-card ${t.status==='已完成'?'task-done':''}`} onClick={()=>setSelected(t.id)}><div><span className="eyebrow">{fieldLabel(t.fieldId)}</span><span className="status-pill">{t.status}</span></div><h3>{t.title}</h3><p>{t.assignee||'等待分派'} · {t.device} · {t.due}</p><footer><span>{t.photos.length} 张作业照片</span>{t.status==='已完成'?<CheckCircle2 size={17}/>:<ArrowRight size={17}/>}</footer></motion.button>])}</AnimatePresence></div>{!list.length&&<EmptyState title="这里还没有任务" detail="调整筛选条件，或新建一次农事作业。"><button className="work-primary" onClick={()=>needLogin()&&setCreating(true)}>新建任务</button></EmptyState>}
 <Sheet open={creating} onClose={()=>setCreating(false)} title="新建农事任务"><form className="work-form" onSubmit={e=>{e.preventDefault();if(!needLogin()||!draft.title.trim())return;const id=createTask({...draft,title:draft.title.trim(),assignee:isAdmin?draft.assignee:''});setCreating(false);setSelected(id);toast('任务已创建')}}><label>任务名称<input required maxLength={60} value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))} placeholder="例如：A1 清晨墒情巡检"/></label><label>作业地块<FieldSelect value={draft.fieldId} onChange={fieldId=>setDraft(d=>({...d,fieldId}))}/></label><div className="form-pair"><label>类型<select value={draft.kind} onChange={e=>setDraft(d=>({...d,kind:e.target.value}))}>{['巡检','灌溉','施药','施肥','采收','复核'].map(v=><option key={v}>{v}</option>)}</select></label><label>计划日期<input type="date" required value={draft.due} onChange={e=>setDraft(d=>({...d,due:e.target.value}))}/></label></div>{isAdmin?<label>负责人<select value={draft.assignee} onChange={e=>setDraft(d=>({...d,assignee:e.target.value}))}><option value="">稍后分派</option>{PEOPLE.map(p=><option key={p}>{p}</option>)}</select></label>:<p className="muted">创建后等待管理员分派。</p>}<label>设备<select value={draft.device} onChange={e=>setDraft(d=>({...d,device:e.target.value}))}>{DEVICES.map(p=><option key={p}>{p}</option>)}</select></label><label>作业说明<textarea value={draft.note} onChange={e=>setDraft(d=>({...d,note:e.target.value}))} maxLength={500}/></label><button className="work-primary" type="submit">创建任务</button></form></Sheet>
 <Sheet open={!!task} onClose={()=>setSelected(null)} title={task?.title??'任务详情'}>{task&&<><div className="task-detail-heading"><span className="status-pill">{task.status}</span>{task.status==='已完成'&&<SuccessMark size={36}/>}<p>{fieldLabel(task.fieldId)} · {task.kind} · {task.due}</p><p>{task.assignee||'尚未分派'} · {task.device}</p><p className="muted">{task.note}</p></div><ol className="task-steps">{TASK_STATES.map((s,i)=><li key={s} data-done={i<=TASK_STATES.indexOf(task.status)}><i/>{s}</li>)}</ol>{task.status==='待分派'?<div className="work-form"><label>负责人<select value={assignee} onChange={e=>setAssignee(e.target.value)}>{PEOPLE.map(p=><option key={p}>{p}</option>)}</select></label><label>设备<select value={device} onChange={e=>setDevice(e.target.value)}>{DEVICES.map(p=><option key={p}>{p}</option>)}</select></label><button className="work-primary" onClick={()=>{if(needAdmin())assignTask(task.id,assignee,device)}}>确认分派</button></div>:task.status!=='已完成'&&<button className="work-primary" onClick={advance}>{task.status==='待执行'?'开始执行':task.status==='执行中'?'提交验收':'验收完成'}</button>}{task.status==='已完成'&&<TaskResult key={task.id} task={task} onViewList={()=>{setSelected(null);setFilter('已完成');setField('all');setQuery('')}}/>}<h3 className="work-section-title">作业照片</h3><div className="photo-grid">{photos.map((p,i)=><motion.button layout key={p.id} initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} onClick={()=>setPhotoIndex(i)}><StoredPhoto src={p.src} alt={p.note}/></motion.button>)}{task.status!=='已完成'&&<label className="upload-button"><Camera size={20}/>{busy?'正在压缩…':'上传照片'}<input disabled={busy} type="file" accept="image/*" onClick={e=>{if(!needLogin())e.preventDefault()}} onChange={file}/></label>}</div>{photoError&&<p role="alert" className="inline-error">{photoError}，可重新选择照片。</p>}{!photos.length&&<p className="muted">上传现场照片后，可提交验收。照片自动汇入地块档案。</p>}<h3 className="work-section-title">操作记录</h3>{state.events.filter(e=>e.taskId===task.id).map(e=><div className="event-line" key={e.id}><i/><div><b>{e.title}</b><p>{new Date(e.at).toLocaleString('zh-CN')}</p></div></div>)}</>}</Sheet><PhotoGallery photos={photos} index={photoIndex} onClose={()=>setPhotoIndex(null)}/></div>
}
