import { useState } from 'react'
import { ShieldAlert, Search, ArrowRight, CheckCircle2, Clock, ScanLine, MapPin } from 'lucide-react'
import { ALERT_PHOTOS } from '../real-media'
import { PhotoReference } from '../components/ImageryCredit'
import { FarmEmpty } from '../components/AgriArtwork'
import { ALERTS, alertTaskTitle, SAMPLES } from '../agronomy'
import { useStore, todayStr, nowTimeStr } from '../store'
import { PageHeader, Modal } from '../components/bits'
import { usePageState } from '../use-page-state'

export default function AlertsPage() {
  const { tasks, addTask, setTaskStatus, members, context, workflow, alertStatus, reviewAlert, openField } = useStore()
  const [filter, setFilter] = usePageState<string>('alert-filter','全部')
  const [query, setQuery] = usePageState<string>('alert-query','')
  const [selected, setSelected] = useState<typeof ALERTS[number] | null>(() => ALERTS.find(a => a.id === context.focusId) || null)
  const [assignee, setAssignee] = useState(members[0]?.name || '未分配')
  const [treatment, setTreatment] = useState(''), [result, setResult] = useState(''), [reviewer, setReviewer] = useState(members[0]?.name || '')
  const scope = ALERTS.filter(a => !context.fieldId || a.field === context.fieldId)
  const getTask = (a: typeof ALERTS[number]) => tasks.find(t => t.sourceId === a.id)
  const filtered = scope.filter(a => (filter === '全部' || alertStatus(a.id) === filter || a.level === filter) && (a.title+a.field+SAMPLES.find(s=>s.id===a.field)?.village).includes(query)).sort((a,b) => (a.level === '高风险' ? 0 : 1) - (b.level === '高风险' ? 0 : 1))
  const select = (a: typeof ALERTS[number]) => { setSelected(a); setTreatment(''); setResult('') }
  const task = selected ? getTask(selected) : undefined
  const save = (passed: boolean) => { if (selected && task && reviewAlert({ alertId: selected.id, taskId: task.id, fieldId: selected.field, reviewer, treatment, result, passed })) { setTreatment(''); setResult('') } }
  return <div><PageHeader title="预警中心" desc="从发现风险、完成作业到独立复核，每一步都有记录。" extra={<span className="green-chip"><ShieldAlert size={14}/>处置与复核分开记录</span>}/>
    <div className="alert-stats">{[{label:'待处置',icon:ShieldAlert},{label:'高风险',icon:ScanLine},{label:'待复核',icon:Clock},{label:'已解决',icon:CheckCircle2}].map(s=><button className="panel" key={s.label} onClick={()=>setFilter(s.label)}><s.icon size={20}/><b>{scope.filter(a=>s.label==='高风险'?a.level==='高风险'&&alertStatus(a.id)!=='已解决':alertStatus(a.id)===s.label).length}</b><span>{s.label}</span></button>)}</div>
    <div className="history-toolbar"><div className="segmented">{['全部','待处置','处理中','待复核','需再处理','已解决','高风险'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search-field"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索预警、村庄或地块"/></label></div>
    <div className="alert-list">{filtered.map(a=><article className="panel alert-card" data-risk={a.level} data-state={alertStatus(a.id)} data-motion-item={'alert-'+a.id} data-status={alertStatus(a.id)} key={a.id}><button className="alert-photo-button" onClick={()=>select(a)} aria-label={'查看'+ALERT_PHOTOS[a.id].title}><img className="alert-photo" src={ALERT_PHOTOS[a.id].image} alt={ALERT_PHOTOS[a.id].title} loading="lazy"/><span>实拍参考 · 点击查看</span></button><div className="alert-main"><div><h3>{a.title}</h3><span className={'risk-pill '+(a.level==='高风险'?'high':'medium')}>{a.level}</span></div><p>{a.detail}</p><small>{a.field} · {SAMPLES.find(s=>s.id===a.field)?.crop}<span>{todayStr()} {a.time}</span><span>{a.source}</span></small></div><div className="alert-action"><span className="green-chip">{alertStatus(a.id)}</span><button className="secondary-btn" onClick={()=>select(a)}>查看与处置 <ArrowRight size={14}/></button><button className="text-btn" onClick={()=>openField('map',a.field,a.id)}><MapPin size={13}/>定位地块</button></div></article>)}{!filtered.length&&<div className="panel empty-state"><FarmEmpty title="当前没有符合条件的预警" description="清除状态与关键词，或切换上方工作范围。" action={()=>{setFilter('全部');setQuery('')}} label="清除筛选"/></div>}</div>
    <p className="data-disclaimer">预警为演示数据；照片为对应风险的公开实拍参考，非该地块采集照片。操作记录保存在当前浏览器。</p>
    <Modal open={!!selected} title="预警详情与复核" onClose={()=>setSelected(null)} width="w-[680px]">{selected&&<div className="alert-detail"><span className="eyebrow">ALERT / {selected.id}</span><h2>{selected.title}</h2><p>{selected.detail}</p><PhotoReference photo={ALERT_PHOTOS[selected.id]}/><div className="context-links"><button className="secondary-btn" onClick={()=>{openField('map',selected.field,selected.id);setSelected(null)}}>定位 {selected.field}<MapPin size={14}/></button><button className="secondary-btn" onClick={()=>{openField('soil',selected.field);setSelected(null)}}>查看采样证据<ArrowRight size={14}/></button></div>
      <div className="workflow-steps alert-timeline" aria-label="预警处理过程"><span className="active">发现风险</span><span className={task?'active':''}>派发任务</span><span className={task?.status==='done'?'active':''}>作业完成</span><span className={alertStatus(selected.id)==='已解决'?'active':''}>独立复核</span></div>
      {!task?<><label className="form-label">处置负责人<select value={assignee} onChange={e=>setAssignee(e.target.value)}>{members.map(m=><option key={m.id}>{m.name}</option>)}</select></label><button className="primary-btn" onClick={()=>addTask({title:alertTaskTitle(selected),sourceId:selected.id,fieldId:selected.field,type:selected.id==='A05'?'灌溉施肥':'植保',assignee,date:todayStr(),time:nowTimeStr()})}>创建处置任务<ArrowRight size={15}/></button></>:<div className="linked-task" data-motion-key={alertStatus(selected.id)}><b>{task.title}</b><p>负责人：{task.assignee} · {alertStatus(selected.id)}</p>{task.status!=='done'?<button className="primary-btn" onClick={()=>setTaskStatus(task.id,'done')}>标记作业完成，进入复核</button>:alertStatus(selected.id)==='已解决'?<span className="green-chip"><CheckCircle2 size={16}/>复核通过，风险已解决</span>:<form className="review-form" onSubmit={e=>{e.preventDefault();save(true)}}><label className="form-label">处置记录<textarea aria-label="处置记录" required value={treatment} maxLength={1200} onChange={e=>setTreatment(e.target.value)} placeholder="记录已完成的现场作业及处理范围"/></label><label className="form-label">复测结果<textarea aria-label="复测结果" required value={result} maxLength={1200} onChange={e=>setResult(e.target.value)} placeholder="填写复测读数、单位、时间或现场复查结论"/></label><label className="form-label">复核人<select aria-label="复核人" value={reviewer} onChange={e=>setReviewer(e.target.value)}>{members.map(m=><option key={m.id}>{m.name}</option>)}</select></label><div className="action-row"><button className="primary-btn" disabled={!treatment.trim()||!result.trim()} type="submit">复核通过，解决预警</button><button className="secondary-btn" disabled={!treatment.trim()||!result.trim()} type="button" onClick={()=>save(false)}>未通过，保留风险</button></div><button type="button" className="text-btn" onClick={()=>setTaskStatus(task.id,'pending')}>重新安排处置任务</button></form>}</div>}
      {workflow.reviews.some(r=>r.alertId===selected.id)&&<section className="review-history"><h3>复核记录</h3>{workflow.reviews.filter(r=>r.alertId===selected.id).map(r=><article key={r.id}><b>{r.passed?'通过':'未通过'} · {r.reviewer}</b><small>{r.at.slice(0,16).replace('T',' ')}</small><p>处置：{r.treatment}</p><p>复测：{r.result}</p></article>)}</section>}
    </div>}</Modal>
  </div>
}
