import { useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Download, Droplets, Leaf, Sprout, RotateCcw, SlidersHorizontal, ChartNoAxesCombined } from 'lucide-react'
import { ResponsiveContainer, AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts'
import { chartTooltip, chartColors } from '../components/chart-theme'
import { PageHeader } from '../components/bits'
import { CropPhoto } from '../components/CropPhoto'
import { Count } from '../components/Motion'
import ResourceFlowScene from '../components/ResourceFlowScene'
import { FIELDS } from '../store'
import { useMotion } from '../components/motion-context'
import { downloadCSV } from '../agronomy'
import { MONTHLY_OPERATIONS, WEEKLY_PRODUCTION, resourceScenario } from '../insight-model'
const RANGES=[{key:'3m',label:'近 3 月',months:3,weeks:12},{key:'6m',label:'近半年',months:6,weeks:26},{key:'12m',label:'近一年',months:12,weeks:52}]
const money=(value:number)=>value.toLocaleString('zh-CN',{maximumFractionDigits:0})
export default function AnalyticsPage(){
 const {enabled}=useMotion()
 const [range,setRange]=useState('6m'),[trend,setTrend]=useState('yield'),[resource,setResource]=useState<'water'|'fertilizer'>('water'),[field,setField]=useState('A1')
 const [waterPrice,setWaterPrice]=useState(2.4),[fertilizerPrice,setFertilizerPrice]=useState(4.8),[waterReduction,setWaterReduction]=useState(0),[fertilizerReduction,setFertilizerReduction]=useState(0)
 const period=RANGES.find(r=>r.key===range)!,monthly=MONTHLY_OPERATIONS.slice(-period.months),weekly=WEEKLY_PRODUCTION.slice(-period.weeks)
 const totals=monthly.reduce((a,m)=>({water:a.water+m.water,fertilizer:a.fertilizer+m.fertilizer,completion:a.completion+m.completion}),{water:0,fertilizer:0,completion:0})
 const totalYield=weekly.reduce((sum,w)=>sum+w.yield,0),avgCompletion=totals.completion/monthly.length
 const scenario=resourceScenario(totals.water,totals.fertilizer,waterPrice,fertilizerPrice,waterReduction,fertilizerReduction)
 const selected=FIELDS.find(f=>f.id===field)!,totalArea=FIELDS.reduce((sum,f)=>sum+f.area,0)
 const peakWater=monthly.reduce((a,b)=>a.water>b.water?a:b),peakYield=weekly.reduce((a,b)=>a.yield>b.yield?a:b)
 const completionChange=monthly.at(-1)!.completion-monthly[0].completion
 const exportScenario=()=>downloadCSV(`惠农-${period.label}-投入情景测算.csv`,[['惠农投入情景测算','演示样本；单价为可编辑假设，非市场报价'],['统计范围',period.label,`${period.months} 个月`],['项目','原用量','调整后用量','单位','假设单价（元）','调整比例（%）'],['灌溉用水',totals.water,scenario.nextWater.toFixed(2),'m³',waterPrice,waterReduction],['肥料',totals.fertilizer,scenario.nextFertilizer.toFixed(2),'kg',fertilizerPrice,fertilizerReduction],['基准投入（元）',scenario.baseline.toFixed(2)],['调整后投入（元）',scenario.next.toFixed(2)],['投入差额（元）',scenario.saving.toFixed(2)],['限制','仅水肥投入；未计人工设备等成本，未模拟减量对产量的影响']])
 return <div className="insights-page operations-lab"><PageHeader title="经营分析" desc="从产量和资源构成出发，观察执行表现，试算不同投入情景。" extra={<div className="segmented">{RANGES.map(r=><button key={r.key} onClick={()=>setRange(r.key)} className={range===r.key?'active':''} aria-pressed={range===r.key}>{r.label}</button>)}</div>}/>
  <div className="insight-summary-grid"><div className="insight-summary featured"><span><ChartNoAxesCombined size={17}/>累计产量</span><b><Count value={totalYield}/><small>吨</small></b><p>最近 {period.weeks} 周 · 演示产量</p></div><div className="insight-summary"><span><Droplets size={17}/>灌溉用水</span><b><Count value={totals.water}/><small>m³</small></b><p>最近 {period.months} 个月累计</p></div><div className="insight-summary"><span><Leaf size={17}/>肥料投入</span><b><Count value={totals.fertilizer}/><small>kg</small></b><p>最近 {period.months} 个月累计</p></div><div className="insight-summary"><span><Sprout size={17}/>农事执行</span><b><Count value={avgCompletion} decimals={1}/><small>%</small></b><p>所选月份完成率的平均值</p></div></div>
  <div className="operations-main-grid"><section className="panel operations-trend"><div className="panel-heading"><div><span className="insight-kicker">投入之外，观察产出与执行</span><h3>{trend==='yield'?'产量变化':'农事完成率'}</h3></div><div className="segmented"><button className={trend==='yield'?'active':''} aria-pressed={trend==='yield'} onClick={()=>setTrend('yield')}>产量</button><button className={trend==='completion'?'active':''} aria-pressed={trend==='completion'} onClick={()=>setTrend('completion')}>执行率</button></div></div><div className="trend-reading"><strong>{trend==='yield'?weekly.at(-1)!.yield:monthly.at(-1)!.completion}<small>{trend==='yield'?'吨 / 周':'%'}</small></strong><span>{trend==='yield'?`最近一周 · ${weekly.at(-1)!.week}`:`最近一月 · ${monthly.at(-1)!.month}`}</span></div>
   <ResponsiveContainer width="100%" height={265}><AreaChart data={trend==='yield'?weekly:monthly} margin={{top:10,right:12,bottom:0,left:-17}}><defs><linearGradient id="operations-trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#527b54" stopOpacity={.25}/><stop offset="100%" stopColor="#527b54" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 6"/><XAxis dataKey={trend==='yield'?'week':'month'} axisLine={false} tickLine={false} minTickGap={28}/><YAxis domain={trend==='yield'?[0,'auto']:[0,100]} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartTooltip}/><Area type="monotone" dataKey={trend==='yield'?'yield':'completion'} name={trend==='yield'?'周产量':'月完成率'} unit={trend==='yield'?' 吨':'%'} stroke="#527b54" fill="url(#operations-trend)" strokeWidth={2.5} isAnimationActive={enabled} animationDuration={450}/></AreaChart></ResponsiveContainer><div className="trend-takeaway"><ArrowUpRight size={17}/><span>{trend==='yield'?`区间峰值出现在 ${peakYield.week}，产量 ${peakYield.yield} 吨。`:`期末较期初${completionChange>=0?'增加':'减少'} ${Math.abs(completionChange)} 个百分点。`}</span></div></section>
   <section className="panel field-portfolio"><div className="panel-heading"><div><span className="insight-kicker">点击地块，查看面积构成</span><h3>种植结构</h3></div><span className="insight-badge">{totalArea.toFixed(1)} 亩</span></div><CropPhoto key={field} fieldId={field} className="portfolio-photo"/><div className="portfolio-selection"><b>{selected.id} {selected.crop}</b><span>{selected.area} 亩 · 占 {(selected.area/totalArea*100).toFixed(1)}%</span></div><div className="field-allocation">{FIELDS.map(f=><button key={f.id} className={field===f.id?'selected':''} aria-pressed={field===f.id} onClick={()=>setField(f.id)}><span>{f.id} {f.crop.replace('（试验）','')}</span><i><em style={{width:`${f.area/totalArea*100}%`}}/></i><b>{(f.area/totalArea*100).toFixed(1)}%</b></button>)}</div><small className="insight-footnote">面积为地块演示档案，不随统计周期改变。</small></section></div>
  <section className="panel resource-planner"><div className="panel-heading"><div><span className="insight-kicker">调整参数，立即看到构成与差额</span><h3><SlidersHorizontal size={19}/>资源投入情景测算</h3></div><button className="secondary-btn" onClick={exportScenario}><Download size={15}/>导出测算</button></div><div className="resource-planner-grid"><div className="resource-flow"><div className="resource-flow-heading"><span>{period.label} · 水肥投入构成</span><small>假设单价测算</small></div><ResourceFlowScene scenario={scenario}/><div className="resource-comparison"><div><span>基准投入</span><b>¥ <Count value={scenario.baseline}/></b></div><ArrowDownRight size={22}/><div><span>预计减少</span><b>¥ <Count value={scenario.saving}/><small>{scenario.savingRate.toFixed(1)}%</small></b></div></div><small>流向图展示基准费用构成，右侧金额按调整参数计算。</small></div>
   <div className="resource-controls"><div className="price-assumptions"><label>水价假设 <span>元 / m³</span><input aria-label="水价假设" type="number" min="0" max="100" step="0.1" value={waterPrice} onChange={e=>setWaterPrice(Math.min(100,Math.max(0,Number(e.target.value))))}/></label><label>肥料单价假设 <span>元 / kg</span><input aria-label="肥料单价假设" type="number" min="0" max="1000" step="0.1" value={fertilizerPrice} onChange={e=>setFertilizerPrice(Math.min(1000,Math.max(0,Number(e.target.value))))}/></label></div><label className="scenario-slider"><span><Droplets size={16}/>用水减量 <b>{waterReduction}%</b></span><input aria-label="用水减量" type="range" min="0" max="30" step="1" value={waterReduction} onChange={e=>setWaterReduction(Number(e.target.value))}/><small>{money(totals.water)} → {money(scenario.nextWater)} m³</small></label><label className="scenario-slider"><span><Leaf size={16}/>肥料减量 <b>{fertilizerReduction}%</b></span><input aria-label="肥料减量" type="range" min="0" max="20" step="1" value={fertilizerReduction} onChange={e=>setFertilizerReduction(Number(e.target.value))}/><small>{money(totals.fertilizer)} → {money(scenario.nextFertilizer)} kg</small></label><button className="text-btn" onClick={()=>{setWaterPrice(2.4);setFertilizerPrice(4.8);setWaterReduction(0);setFertilizerReduction(0)}}><RotateCcw size={14}/>重置测算参数</button><p className="scenario-caveat">单价为可编辑假设，并非市场报价。仅测算水肥投入，未计人工、设备等成本，也未模拟减量对产量的影响。</p></div></div></section>
  <div className="operations-bottom-grid"><section className="panel"><div className="panel-heading"><div><span className="insight-kicker">不同单位，分别观察</span><h3>月度资源用量</h3></div><div className="segmented"><button className={resource==='water'?'active':''} aria-pressed={resource==='water'} onClick={()=>setResource('water')}>用水 m³</button><button className={resource==='fertilizer'?'active':''} aria-pressed={resource==='fertilizer'} onClick={()=>setResource('fertilizer')}>肥料 kg</button></div></div><ResponsiveContainer width="100%" height={220}><BarChart data={monthly} margin={{top:15,right:10,left:-15,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 6"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip contentStyle={chartTooltip}/><Bar dataKey={resource} name={resource==='water'?'用水':'肥料'} unit={resource==='water'?' m³':' kg'} fill={resource==='water'?chartColors.water:chartColors.green} radius={[5,5,0,0]} maxBarSize={38} isAnimationActive={enabled} animationDuration={450}/></BarChart></ResponsiveContainer></section><section className="panel operations-observations"><span className="insight-kicker">所选区间的三个观察</span><h3>本期经营观察</h3><ol><li><span>01</span><div><b>{peakWater.month} 用水量最高</b><p>{money(peakWater.water)} m³，占所选月份总用水的 {(peakWater.water/totals.water*100).toFixed(1)}%。</p></div></li><li><span>02</span><div><b>期末执行率 {monthly.at(-1)!.completion}%</b><p>较期初{completionChange>=0?'上升':'下降'} {Math.abs(completionChange)} 个百分点。</p></div></li><li><span>03</span><div><b>{selected.crop}占在管面积 {(selected.area/totalArea*100).toFixed(1)}%</b><p>可切换种植结构中的地块查看构成；未按地块分配产量。</p></div></li></ol></section></div>
  <p className="data-disclaimer">本页为经营分析演示：产量按最近 {period.weeks} 周统计，水肥与完成率按最近 {period.months} 个月统计，均非实测经营记录。</p>
 </div>
}
