import { useEffect, useState } from 'react'
import { ArrowUpRight, Droplets, Thermometer, Wind } from 'lucide-react'
import { FIELDS, useStore } from '../store'
import { SAMPLES, soilHistory, soilMetrics } from '../agronomy'
import { FarmMapSVG } from './FarmMapSVG'
import { ImageryCredit } from './ImageryCredit'
import { useMotion } from './motion-context'
import { Count } from './Motion'
export default function DigitalTwinOverview(){
 const [selected,setSelected]=useState('A1');const [progress,setProgress]=useState(12)
 const {setPage,readings}=useStore();const {enabled}=useMotion()
 useEffect(()=>{if(!enabled)return;const id=setInterval(()=>{if(!document.hidden)setProgress(p=>(p+.3)%100)},600);return()=>clearInterval(id)},[enabled])
 const field=FIELDS.find(f=>f.id===selected)!;const sample=SAMPLES.find(s=>s.id===selected)!;const moisture=soilMetrics(sample)[1];const history=soilHistory(selected,7)
 const points=history.map((h,i)=>`${i*40},${65-(h.moisture-Math.min(...history.map(x=>x.moisture)))*7}`).join(' ')
 return <div className="twin-grid"><section className="panel twin-primary"><div className="twin-heading"><div><span className="eyebrow">LAND · LIFE · INTELLIGENCE</span><h2>田块与巡检 <small>空间概览</small></h2></div><button className="text-btn" onClick={()=>setPage('map')}>全屏地图 <ArrowUpRight size={16}/></button></div><div className="twin-map"><FarmMapSVG layers={{fields:true,monitors:false,irrigation:false}} selectedField={selected} onFieldClick={setSelected} patrol={{progress,running:enabled}}/><span className="twin-map-caption"><i/> ROVER 01 · 路线模拟</span></div><div className="twin-fields" aria-label="选择演示地块">{FIELDS.map(f=><button key={f.id} aria-pressed={selected===f.id} onClick={()=>setSelected(f.id)}>{f.id}<span>{f.crop.replace('（试验）','')}</span></button>)}</div><div className="twin-field-info"><div><small>当前地块</small><b>{field.id} · {field.crop}</b></div><div><small>种植面积</small><b>{field.area}<em> 亩</em></b></div><div><small>土壤 pH</small><b>{sample.ph}</b></div><button className="primary-btn" onClick={()=>{try{sessionStorage.setItem('huinong-soil-field',selected)}catch{/* optional navigation context */}setPage('soil')}}>土壤报告 <ArrowUpRight size={15}/></button></div><ImageryCredit/></section>
 <section className="panel environment-card"><div className="panel-heading"><div><span className="eyebrow">GROWING CONDITIONS</span><h3>田间生长环境</h3></div><Droplets size={23}/></div><div className="environment-field">{field.id} {field.crop}<span>采样演示 · 08:30</span></div><div className="moisture-gauge"><svg viewBox="0 0 200 120" aria-hidden="true"><path d="M20 100a80 80 0 0 1 160 0" pathLength="100" className="gauge-track"/><path d="M20 100a80 80 0 0 1 160 0" pathLength="100" className="gauge-value" strokeDasharray={`${sample.soilMoisture} 100`}/></svg><div><b><Count value={sample.soilMoisture}/><small>%</small></b><span>土壤含水量</span></div></div><p className={`environment-status ${moisture.warning?'is-warning':''}`}>{moisture.warning?'需要关注':'适宜范围'}<span>演示参考 {moisture.range}%</span></p><div className="environment-spark"><span>近 7 日水分趋势</span><svg viewBox="0 0 240 85" role="img" aria-label={`水分趋势：${history.map(h=>h.moisture+'%').join('，')}`}><polyline points={points} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div><small>{history[0].label}</small><small>{history[6].label}</small></div></div><div className="environment-readings"><div><Thermometer size={16}/><span>空气温度</span><b>{(readings.D4?.v1??26).toFixed(1)}<small> °C</small></b></div><div><Wind size={16}/><span>空气湿度</span><b>{Math.round(readings.D4?.v2??65)}<small> %</small></b></div></div><button className="text-btn" onClick={()=>setPage('devices')}>查看环境设备 <ArrowUpRight size={15}/></button><small className="environment-note">气象数值为模拟变化，未连接现场传感器</small></section></div>
}
