import {useEffect,useRef,useState} from 'react'
import {MonitorPlay,Maximize,Pause,Play,X} from 'lucide-react'
import {useStore,type PageKey} from '../store'
import {useMotion} from './motion-context'
import {feedback} from '../feedback'
const scenes:{page:PageKey;label:string}[]=[{page:'dashboard',label:'农场总览'},{page:'map',label:'田间地图'},{page:'inspection',label:'智能巡检'},{page:'harvest',label:'采收展望'}]
export default function PresentationMode(){const {page,setPage}=useStore();const {enabled}=useMotion();const [active,setActive]=useState(false);const [auto,setAuto]=useState(false);const [seconds,setSeconds]=useState(15);const previous=useRef<PageKey>('dashboard');const ownsFullscreen=useRef(false);const trigger=useRef<HTMLButtonElement>(null)
 const finish=()=>{setActive(false);setAuto(false);setPage(previous.current);if(ownsFullscreen.current&&document.fullscreenElement)document.exitFullscreen().catch(()=>{});ownsFullscreen.current=false;requestAnimationFrame(()=>trigger.current?.focus())}
 const finishRef=useRef(finish);useEffect(()=>{finishRef.current=finish})
 useEffect(()=>{document.documentElement.dataset.presenting=String(active);if(!active)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!document.querySelector('[role="dialog"]'))finishRef.current();else if(!(e.target as Element).closest('.presentation-controls'))setAuto(false)};const fullscreen=()=>{if(ownsFullscreen.current&&!document.fullscreenElement)finishRef.current()};const interact=(e:Event)=>{if(!(e.target as Element).closest('.presentation-controls'))setAuto(false)};document.addEventListener('keydown',key);document.addEventListener('fullscreenchange',fullscreen);document.addEventListener('pointerdown',interact);return()=>{document.documentElement.dataset.presenting='false';document.removeEventListener('keydown',key);document.removeEventListener('fullscreenchange',fullscreen);document.removeEventListener('pointerdown',interact)}},[active])
 useEffect(()=>{if(!active||!auto||!enabled)return;const timer=setTimeout(()=>{if(document.hidden||document.querySelector('[role="dialog"]')){setAuto(false);return}if(seconds<=1){setPage(scenes[(scenes.findIndex(s=>s.page===page)+1)%scenes.length].page);setSeconds(15)}else setSeconds(seconds-1)},1000);return()=>clearTimeout(timer)},[active,auto,enabled,seconds,page,setPage])
 const fullscreen=()=>{if(document.fullscreenElement)return;if(!document.documentElement.requestFullscreen){feedback('当前浏览器不支持全屏，已保留展示布局');return}document.documentElement.requestFullscreen().then(()=>{ownsFullscreen.current=true}).catch(()=>feedback('浏览器未进入全屏，已保留展示布局'))}
 return <><button ref={trigger} className="icon-btn presentation-trigger" title="项目展示模式" aria-label="项目展示模式" onClick={()=>{previous.current=page;setActive(true);setPage('dashboard');setSeconds(15)}}><MonitorPlay size={18}/></button>{active&&<div className="presentation-controls" role="region" aria-label="展示控制"><span className="presentation-brand">惠农<span> FIELD STORIES / 演示</span></span><div className="presentation-scenes">{scenes.map((s,i)=><button key={s.page} aria-pressed={page===s.page} onClick={()=>{setPage(s.page);setSeconds(15)}}><small>0{i+1}</small>{s.label}</button>)}</div><div className="presentation-actions"><button onClick={()=>{setAuto(v=>!v);setSeconds(15)}} disabled={!enabled} title={!enabled?'开启动画后可自动轮播':undefined}>{auto&&enabled?<Pause size={15}/>:<Play size={15}/>}<span>{auto&&enabled?seconds+' 秒后切换':'自动轮播'}</span></button><button onClick={fullscreen} aria-label="进入浏览器全屏"><Maximize size={17}/></button><button onClick={finish} aria-label="退出展示模式"><X size={18}/></button></div></div>}</>}
