import { useState } from 'react'
import { Plus, Download, ArrowUpRight, ReceiptText } from 'lucide-react'
import { useStore, FIELDS, todayStr } from '../store'
import { LEDGER_NAMES, ledgerTotals, validLedger, type LedgerKind, type LedgerEntry } from '../workflow-model'
import { downloadCSV } from '../agronomy'
import { Modal } from './bits'
import { Count } from './Motion'

export default function ProductionLedger() {
  const { context, workflow, tasks, addLedger, removeLedger, openField } = useStore()
  const [kind,setKind]=useState<LedgerKind|'all'>('all'),[from,setFrom]=useState(context.date.slice(0,7)+'-01'),[to,setTo]=useState(context.date)
  const [open,setOpen]=useState(context.focusId==='new-harvest'),[detail,setDetail]=useState<LedgerEntry|null>(null)
  const [entryKind,setEntryKind]=useState<'harvest'|'labor'|'water'>('harvest'),[field,setField]=useState(context.fieldId||'A1'),[date,setDate]=useState(context.date),[taskId,setTaskId]=useState('')
  const [quantity,setQuantity]=useState(''),[price,setPrice]=useState(''),[loss,setLoss]=useState('0'),[title,setTitle]=useState('')
  const scope=workflow.ledger.filter(e=>(!context.fieldId||e.fieldId===context.fieldId)&&e.date>=from&&e.date<=to)
  const entries=scope.filter(e=>kind==='all'||e.kind===kind).sort((a,b)=>b.date.localeCompare(a.date))
  const area=FIELDS.filter(f=>!context.fieldId||f.id===context.fieldId).reduce((n,f)=>n+f.area,0),totals=ledgerTotals(scope,area)
  const unit=entryKind==='harvest'?'kg':entryKind==='labor'?'小时':'m³'
  const draft={fieldId:field,date,kind:entryKind,title:title.trim()||LEDGER_NAMES[entryKind],quantity:Number(quantity),unit,unitPrice:entryKind==='harvest'?0:Number(price),loss:entryKind==='harvest'?Number(loss):0,taskId:taskId||undefined}
  const valid=quantity.trim()!==''&&(entryKind==='harvest'||price.trim()!=='')&&validLedger(draft)&&date<=todayStr()
  const submit=()=>{if(valid&&addLedger(draft)){setOpen(false);setQuantity('');setPrice('');setLoss('0');setTitle('')}}
  const exportRows=()=>downloadCSV(`生产账本-${from}-${to}.csv`,[['数据来源','本机录入，非自动采集'],['日期','地块','类型','内容','数量','单位','单价','损耗 kg','计入投入 元','任务编号'],...entries.map(e=>[e.date,e.fieldId,LEDGER_NAMES[e.kind],e.title,e.quantity,e.unit,e.unitPrice,e.loss,['harvest','stock-in'].includes(e.kind)?0:e.quantity*e.unitPrice,e.taskId||'未关联'])])
  return <section className="production-ledger"><div className="panel-heading"><div><span className="insight-kicker">每一笔记录，都能追溯</span><h2>生产账本</h2></div><div className="action-row"><button className="secondary-btn" onClick={exportRows}><Download size={15}/>导出账本</button><button className="primary-btn" onClick={()=>{setField(context.fieldId||'A1');setTaskId('');setDate(context.date);setOpen(true)}}><Plus size={15}/>记录生产</button></div></div>
    <div className="ledger-toolbar"><label>起始日期<input type="date" aria-label="账本起始日期" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>截至日期<input type="date" aria-label="账本截至日期" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><span>本机记录 · {scope.length} 笔 · {context.fieldId||'全部地块'}</span></div>
    <div className="ledger-metrics" data-motion-key={`${scope.length}-${totals.cost}-${totals.harvest}`}><button onClick={()=>setKind('all')}><span>已记录投入</span><b>¥<Count value={totals.cost} decimals={2}/></b><small>领料 + 人工 + 用水</small></button><button onClick={()=>setKind('all')}><span>亩均已记录投入</span><b>¥<Count value={totals.perMu} decimals={2}/></b><small>按所选在管面积 {area.toFixed(1)} 亩分摊</small></button><button onClick={()=>setKind('harvest')}><span>采收净重</span><b><Count value={totals.harvest}/><small> kg</small></b><small>实重扣除损耗 {totals.loss} kg</small></button><button onClick={()=>setKind('labor')}><span>已记录工时</span><b><Count value={scope.filter(e=>e.kind==='labor').reduce((n,e)=>n+e.quantity,0)}/><small> 小时</small></b><small>可点选查看明细</small></button></div>
    <div className="ledger-register panel"><div className="ledger-filter segmented">{(['all','material','water','labor','harvest','stock-in'] as const).map(k=><button key={k} aria-pressed={kind===k} className={kind===k?'active':''} onClick={()=>setKind(k)}>{k==='all'?'全部记录':LEDGER_NAMES[k]}</button>)}</div>{entries.length?<div className="ledger-rows">{entries.map(e=><button className="ledger-row" key={e.id} data-motion-item={'ledger-'+e.id} onClick={()=>setDetail(e)}><span><small>{e.date} · {e.fieldId}</small><b>{e.title}</b></span><span>{LEDGER_NAMES[e.kind]}</span><span>{e.quantity} {e.unit}{e.kind==='harvest'&&<small>损耗 {e.loss} kg</small>}</span><strong>{e.kind==='harvest'?`${e.quantity-e.loss} kg`:'¥'+(e.quantity*e.unitPrice).toFixed(2)}<small>{e.kind==='stock-in'?'采购额 · 不计生产投入':e.kind==='harvest'?'采收净重':'已记录投入'}</small></strong><ArrowUpRight size={15}/></button>)}</div>:<div className="ledger-empty"><ReceiptText size={32}/><h3>当前范围还没有生产记录</h3><p>先记录一笔采收、工时或用水，物资出库也会自动进入账本。</p><button className="text-btn" onClick={()=>openField('inventory',context.fieldId)}>前往登记领料 <ArrowUpRight size={14}/></button></div>}</div>
    <p className="data-disclaimer">统计仅覆盖已录入记录，不等于农场全部成本或利润；入库金额不重复计入生产投入。采收数量均为 kg，不与演示吨数混合。</p>
    <Modal open={open} title="记录生产投入与采收" onClose={()=>setOpen(false)} width="w-[600px]"><form className="ledger-form" onSubmit={e=>{e.preventDefault();submit()}}><div className="form-two"><label className="form-label">记录类型<select aria-label="生产记录类型" value={entryKind} onChange={e=>{setEntryKind(e.target.value as typeof entryKind);setQuantity('');setPrice('');setLoss('0')}}><option value="harvest">采收实重</option><option value="labor">人工工时</option><option value="water">灌溉用水</option></select></label><label className="form-label">地块<select aria-label="生产地块" value={field} onChange={e=>{setField(e.target.value);setTaskId('')}}>{FIELDS.map(f=><option key={f.id} value={f.id}>{f.id} {f.crop}</option>)}</select></label><label className="form-label">记录日期<input type="date" aria-label="生产日期" required max={todayStr()} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="form-label">关联任务<select aria-label="生产关联任务" value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">暂不关联</option>{tasks.filter(t=>t.fieldId===field).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="form-label">数量（{unit}）<input aria-label="生产数量" required type="number" min="0.001" max="10000000" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>{entryKind==='harvest'?<label className="form-label">损耗（kg）<input aria-label="采收损耗" required type="number" min="0" max={quantity||0} step="any" value={loss} onChange={e=>setLoss(e.target.value)}/></label>:<label className="form-label">单价（元 / {unit}）<input aria-label="生产单价" required type="number" min="0" max="10000000" step="any" value={price} onChange={e=>setPrice(e.target.value)}/></label>}</div><label className="form-label">记录说明<input aria-label="生产说明" maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="批次、作业内容或记录人"/></label><p>肥料、种子等领用请在物资管理中出库，系统同步库存与账本。</p><button className="primary-btn" disabled={!valid}>保存生产记录</button></form></Modal>
    <Modal open={!!detail} title="生产记录凭据" onClose={()=>setDetail(null)} width="w-[540px]">{detail&&<div className="ledger-receipt"><h2>{detail.title}</h2><dl><div><dt>记录编号</dt><dd>{detail.id}</dd></div><div><dt>日期 / 地块</dt><dd>{detail.date} / {detail.fieldId}</dd></div><div><dt>数量 / 单价</dt><dd>{detail.quantity} {detail.unit} / ¥{detail.unitPrice}</dd></div><div><dt>关联任务</dt><dd>{tasks.find(t=>t.id===detail.taskId)?.title||'未关联'}</dd></div><div><dt>来源</dt><dd>{detail.inventoryId?'物资出入库同步':'本机录入'}</dd></div></dl><p>撤销会同步更新账本、事件复盘及关联库存。</p><button className="secondary-btn" onClick={()=>{removeLedger(detail.id);setDetail(null)}}>撤销这笔记录</button></div>}</Modal>
  </section>
}
