"""Build local variable webfonts from the OFL-licensed Noto Sans SC source.

Usage: python scripts/build-ui-font.py /path/to/NotoSansSC.ttf
Requires fonttools[woff] and brotli. Source and license are documented in
src/assets/fonts/README.md. No network is needed at website runtime.
"""
import hashlib
from pathlib import Path
import sys
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1])
destination = root / "src/assets/fonts"
destination.mkdir(parents=True, exist_ok=True)
coverage = set(TTFont(source).getBestCmap())
interface = set(range(0x20, 0x250)) | set(range(0x2000, 0x2070))
for path in (root / "src").rglob("*"):
    if path.suffix in {".ts", ".tsx"}:
        interface.update(map(ord, path.read_text(encoding="utf-8")))
interface &= coverage
common = set()
for first in range(0xA1, 0xF8):
    for second in range(0xA1, 0xFF):
        try:
            common.update(map(ord, bytes([first, second]).decode("gb2312")))
        except UnicodeDecodeError:
            pass
common = (common & coverage) - interface

def unicode_ranges(codepoints):
    ranges = []
    start = previous = None
    for value in sorted(codepoints):
        if previous is not None and value != previous + 1:
            ranges.append(f"U+{start:X}" if start == previous else f"U+{start:X}-{previous:X}")
            start = value
        if start is None:
            start = value
        previous = value
    if start is not None:
        ranges.append(f"U+{start:X}" if start == previous else f"U+{start:X}-{previous:X}")
    return ",".join(ranges)

css = ["/* Generated by scripts/build-ui-font.py; locally served, OFL licensed. */"]
for name, codepoints in [("interface", interface), ("common", common)]:
    font = TTFont(source)
    options = subset.Options()
    options.hinting = True
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    options.layout_features = ["*"]
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=codepoints)
    sub.subset(font)
    font.flavor = "woff2"
    target = destination / f"noto-sans-sc-{name}.woff2"
    font.save(target)
    css.append("@font-face {\n  font-family:'Huinong Sans';\n  font-style:normal;\n  font-weight:100 900;\n  font-display:swap;\n  src:url('./assets/fonts/" + target.name + "') format('woff2');\n  unicode-range:" + unicode_ranges(codepoints) + ";\n}")
    print(f"{name}: {len(codepoints)} codepoints, {target.stat().st_size:,} bytes")
(root / "src/fonts.css").write_text("\n".join(css) + "\n", encoding="utf-8")
print("source sha256:", hashlib.sha256(source.read_bytes()).hexdigest())
